default_platform(:android)

platform :android do
  desc "Upload APK to Amazon Appstore (no commit)"
  lane :amazon_upload do
    upload_to_amazon_appstore(
      client_id: "amzn1.application-oa2-client.8e334808268a48b59172123b0380bbb2",
      client_secret: "ea2f283a48ef91b8c3889fbb4175e4acc9799b665c99ce5eb359a5fe425f03d9",
      package_name: "amzn1.devportal.mobileapp.8cb5f36a3d8e4ee99da77d979e0d377f",
      apk: 'C:\Users\David\Downloads\MTD_3.94.13287_Release_Amazon.apk',
      skip_upload_changelogs: true,
      changes_not_sent_for_review: true,
      overwrite_upload: true,
      overwrite_upload_mode: "new",
      timeout: 600
    )
  end
end
